apiVersion: v1
kind: ConfigMap
metadata:
  namespace: basket
  name: serviceconfig
  labels:
    app: simple-shop
    team: alpha
data:
  svcconfig: |-
    {
      "logging": {
        "logLevel": {
          "default": "Information"
        },
        "logger": "fluentd"
      },
      
      "bus": {
        "receiveEndpoint": "basket",
        "host": "queue.data",
        "username": "guest",
        "password": "guest"
      },
      
      "redis":{
        "connectionString": "cache.data"
      }
    }

