apiVersion: v1
kind: Service
metadata:
  namespace: basket
  labels:
    app: simple-shop
    component: basket
  name: basket
spec:
  ports:
  - name: http
    protocol: TCP
    port: 7001
    targetPort: 7001
  selector:
    app: simple-shop
    component: basket