apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: basket
  name: basket
spec:
  paused: true
  template:
    metadata:
      labels:
        app: simple-shop
        component: basket
        team: alpha
    spec:
      containers:
        - name: basket
          image: dbonessimplestore/basket
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 250
              memory: 512Mi
            requests:
              memory: 256Mi
      volumes:
        - name: config
          configMap:
            name: serviceconfig
            items:
              - key: svcconfig
                path: /app/stagesettings.json